package dev.abu.my_bot;

public interface BotQuery {
    String UZ_SELECT = "UZ_SELECT";
    String RU_SELECT = "RU_SELECT";
    String RU_SELECT1 = "RU_SELECT1";
    String RU_SELECT2 = "RU_SELECT2";
    String ENG_SELECT1 = "ENG_SELECT1";
    String ENG_SELECT2 = "ENG_SELECT2";
    String ENG_SELECT = "ENG_SELECT";
    String START_TEST = "START_TEST";
    String START_TEST1 = "START_TEST1";
    String IQ_START = "IQ_START";
    String IQ_START1 = "IQ_START1";
    String IQ_START2 = "IQ_START2";
    String IQ_START3 = "IQ_START3";
    String IQ_START4 = "IQ_START4";
    String IQ_START5 = "IQ_START5";
    String IQ_START6 = "IQ_START6";
    String IQ_START7 = "IQ_START7";
    String IQ_START8 = "IQ_START8";
    String IQ_START9 = "IQ_START9";
    String IQ_START10 = "IQ_START10";
    String IQ_START2T = "IQ_START2T";
    String IQ_START3T = "IQ_START3T";
    String IQ_START4T = "IQ_START4T";
    String IQ_START5T = "IQ_START5T";
    String IQ_START6T = "IQ_START6T";
    String IQ_START7T = "IQ_START7T";
    String IQ_START8T = "IQ_START8T";
    String IQ_START9T = "IQ_START9T";
    String IQ_START10T = "IQ_START10T";
    String DAS_START1 = "DAS_START";
    String DAS_START2 = "DAS_START";
    String TEST_DASTUR1 = "TEST_DASTUR1";
    String TEST_DASTUR1T = "TEST_DASTUR1T";
    String TEST_DASTUR2 = "TEST_DASTUR2";
    String TEST_DASTUR2T = "TEST_DASTUR2T";
    String TEST_DASTUR3 = "TEST_DASTUR3";
    String TEST_DASTUR3T = "TEST_DASTUR3T";
    String TEST_DASTUR4 = "TEST_DASTUR4";
    String TEST_DASTUR4T = "TEST_DASTUR4T";
    String TEST_DASTUR5 = "TEST_DASTUR5";
    String TEST_DASTUR5T = "TEST_DASTUR5T";
    String TEST_DASTUR6 = "TEST_DASTUR6";
    String TEST_DASTUR6T = "TEST_DASTUR6T";
    String TEST_DASTUR7 = "TEST_DASTUR7";
    String TEST_DASTUR7T = "TEST_DASTUR7T";
    String TEST_DASTUR8 = "TEST_DASTUR8";
    String TEST_DASTUR8T = "TEST_DASTUR8T";
    String TEST_DASTUR9 = "TEST_DASTUR9";
    String TEST_DASTUR9T = "TEST_DASTUR9T";
    String TEST_DASTUR10 = "TEST_DASTUR10";
    String TEST_DASTUR10T = "TEST_DASTUR10T";
    String IQ_LAST = "IQ_LAST";



}
